# Generated by Django 5.2.4 on 2025-07-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('nome_all', models.CharField(db_column='Nome_all', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Allergene',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('nome_ingr', models.CharField(db_column='Nome_ingr', max_length=50, primary_key=True, serialize=False)),
                ('calorie', models.IntegerField(db_column='Calorie')),
            ],
            options={
                'db_table': 'Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('tipologia', models.CharField(db_column='Tipologia', max_length=50, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(db_column='Descrizione', max_length=255)),
                ('prezzo', models.DecimalField(blank=True, db_column='Prezzo', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id_personale', models.AutoField(db_column='ID_personale', primary_key=True, serialize=False)),
                ('nome_pers', models.CharField(db_column='Nome_pers', max_length=100)),
                ('ruolo', models.CharField(db_column='Ruolo', max_length=9)),
            ],
            options={
                'db_table': 'Personale',
            },
        ),
        migrations.CreateModel(
            name='Sconto',
            fields=[
                ('nclient_sconto', models.IntegerField(db_column='nClient_Sconto', primary_key=True, serialize=False)),
                ('percentuale', models.DecimalField(db_column='Percentuale', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Sconto',
            },
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('id_tavolo', models.IntegerField(db_column='ID_tavolo', primary_key=True, serialize=False)),
                ('tipologia', models.CharField(blank=True, db_column='Tipologia', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tavolo',
            },
        ),
        migrations.CreateModel(
            name='OrarioServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_lavoro', models.CharField(db_column='Turno_lavoro', max_length=20)),
                ('data_turno', models.DateField(db_column='Data_turno')),
            ],
            options={
                'db_table': 'Orario_servizio',
                'unique_together': {('turno_lavoro', 'data_turno')},
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('nome_piatto', models.CharField(db_column='Nome_piatto', max_length=100, primary_key=True, serialize=False)),
                ('foto', models.CharField(db_column='Foto', max_length=255)),
                ('descrizione', models.CharField(db_column='Descrizione', max_length=255)),
                ('prezzo', models.DecimalField(blank=True, db_column='Prezzo', decimal_places=2, max_digits=8, null=True)),
                ('tipologia', models.ForeignKey(db_column='Tipologia', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.menu')),
            ],
            options={
                'db_table': 'Piatto',
            },
        ),
        migrations.CreateModel(
            name='PiattoPreparato',
            fields=[
                ('id_piatto', models.AutoField(db_column='ID_piatto', primary_key=True, serialize=False)),
                ('stato', models.CharField(db_column='Stato', max_length=50)),
                ('nome_piatto', models.ForeignKey(db_column='Nome_piatto', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.piatto')),
            ],
            options={
                'db_table': 'Piatto_Preparato',
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id_pren', models.AutoField(db_column='ID_Pren', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='Data')),
                ('orario', models.TimeField(db_column='Orario')),
                ('turno', models.CharField(db_column='Turno', max_length=20)),
                ('username', models.ForeignKey(db_column='Username', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.cliente')),
            ],
            options={
                'db_table': 'Prenotazione',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pag', models.AutoField(db_column='ID_pag', primary_key=True, serialize=False)),
                ('importo', models.DecimalField(db_column='Importo', decimal_places=2, max_digits=8)),
                ('data', models.DateField(db_column='Data')),
                ('tipologia', models.CharField(db_column='Tipologia', max_length=50)),
                ('nclient_sconto', models.ForeignKey(blank=True, db_column='nClient_Sconto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.sconto')),
                ('id_tavolo', models.ForeignKey(db_column='ID_tavolo', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.tavolo')),
            ],
            options={
                'db_table': 'Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordine', models.IntegerField(db_column='ID_ordine')),
                ('npiatti', models.IntegerField(db_column='nPiatti')),
                ('id_tavolo', models.ForeignKey(db_column='ID_tavolo', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.tavolo')),
            ],
            options={
                'db_table': 'Ordine',
                'unique_together': {('id_tavolo', 'id_ordine')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tavolo',
            field=models.ForeignKey(blank=True, db_column='ID_tavolo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.tavolo'),
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingr', models.ForeignKey(db_column='Nome_ingr', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.ingrediente')),
                ('nome_piatto', models.ForeignKey(db_column='Nome_piatto', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.piatto')),
            ],
            options={
                'db_table': 'Formato',
                'unique_together': {('nome_ingr', 'nome_piatto')},
            },
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_ordine', models.IntegerField(db_column='Max_ordine')),
                ('tipologia', models.ForeignKey(db_column='Tipologia', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.menu')),
                ('nome_piatto', models.ForeignKey(db_column='Nome_piatto', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.piatto')),
            ],
            options={
                'db_table': 'Contiene',
                'unique_together': {('nome_piatto', 'tipologia')},
            },
        ),
        migrations.CreateModel(
            name='Possiede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letalita', models.CharField(db_column='Letalita', max_length=20)),
                ('nome_all', models.ForeignKey(db_column='Nome_all', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.allergene')),
                ('nome_ingr', models.ForeignKey(db_column='Nome_ingr', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.ingrediente')),
            ],
            options={
                'db_table': 'Possiede',
                'unique_together': {('nome_all', 'nome_ingr')},
            },
        ),
        migrations.CreateModel(
            name='Prepara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personale', models.ForeignKey(db_column='ID_personale', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.personale')),
                ('id_piatto', models.ForeignKey(db_column='ID_piatto', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.piattopreparato')),
            ],
            options={
                'db_table': 'Prepara',
                'unique_together': {('id_personale', 'id_piatto')},
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_lavoro', models.CharField(db_column='Turno_lavoro', max_length=20)),
                ('data_turno', models.DateField(db_column='Data_turno')),
                ('id_personale', models.ForeignKey(db_column='ID_personale', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.personale')),
            ],
            options={
                'db_table': 'Servizio',
                'unique_together': {('id_personale', 'turno_lavoro', 'data_turno')},
            },
        ),
        migrations.CreateModel(
            name='PrenotaT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pren', models.ForeignKey(db_column='ID_Pren', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.prenotazione')),
                ('id_tavolo', models.ForeignKey(db_column='ID_tavolo', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.tavolo')),
            ],
            options={
                'db_table': 'Prenota_T',
                'unique_together': {('id_pren', 'id_tavolo')},
            },
        ),
        migrations.CreateModel(
            name='Composizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('id_ordine', models.ForeignKey(db_column='ID_ordine', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.ordine')),
                ('nome_piatto', models.ForeignKey(db_column='Nome_piatto', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.piatto')),
                ('id_tavolo', models.ForeignKey(db_column='ID_tavolo', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.tavolo')),
            ],
            options={
                'db_table': 'Composizione',
                'unique_together': {('nome_piatto', 'id_tavolo', 'id_ordine')},
            },
        ),
        migrations.CreateModel(
            name='Trasporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ordine', models.ForeignKey(db_column='ID_ordine', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.ordine')),
                ('id_personale', models.ForeignKey(db_column='ID_personale', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.personale')),
                ('id_tavolo', models.ForeignKey(db_column='ID_tavolo', on_delete=django.db.models.deletion.DO_NOTHING, to='sushi3.tavolo')),
            ],
            options={
                'db_table': 'Trasporto',
                'unique_together': {('id_tavolo', 'id_ordine', 'id_personale')},
            },
        ),
    ]
