# Generated by Django 5.2.4 on 2025-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='attivo',
            field=models.IntegerField(db_column='Attivo', default=0),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='id_ordine',
            field=models.AutoField(db_column='ID_ordine', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='piatto',
            name='tipologia',
            field=models.CharField(db_column='Tipologia', max_length=50),
        ),
    ]
